using Volo.Abp;

namespace SilviculturePlantsRequest.EntityFrameworkCore;

public abstract class SilviculturePlantsRequestEntityFrameworkCoreTestBase : SilviculturePlantsRequestTestBase<SilviculturePlantsRequestEntityFrameworkCoreTestModule>
{

}
