using SilviculturePlantsRequest.EntityFrameworkCore;
using Xunit;

namespace SilviculturePlantsRequest.EntityFrameworkCore;

public class SilviculturePlantsRequestEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<SilviculturePlantsRequestEntityFrameworkCoreFixture>
{

}
